trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

stages:
- stage: Test
  displayName: 'Test'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: RunTests
    displayName: 'Run Tests'
    steps:
    - script: |
        echo "Running tests..."
        # Insert your test commands here

- stage: Build
  displayName: 'Build'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
  dependsOn: Test
  jobs:
  - job: BuildJob
    displayName: 'Build Project'
    steps:
    - script: |
        echo "Building project..."
        # Insert your build commands here

