trigger:
  branches:
    include:
      - main
      - cicd
      - release

pr:
  branches:
    include:
      - main
      - release

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  displayName: 'Test'
  jobs:
  - job: RunTests
    displayName: 'Run Tests'
    steps:
    - script: |
        echo "Running tests..."
        # Insert your test commands here

- stage: Build
  displayName: 'Build'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/cicd', 'refs/heads/release'))
  dependsOn: Test
  jobs:
  - job: BuildJob
    displayName: 'Build Project'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Use Node.js 20.x'
    - script: npm install
      displayName: 'Install dependencies'
    - script: npm run build 
      displayName: 'Build Angular Project'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'dist/angular-ui/browser'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Archive build output'
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: '$(Build.BuildId).zip'
      displayName: 'Publish artifact to release'

