trigger:
  branches:
    include:
      - main
      - cicd
      - release

pr:
  branches:
    include:
      - main
      - release

stages:
- stage: Test
  displayName: 'Test'
  condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/cicd'))
  jobs:
  - job: RunTests
    displayName: 'Run Tests'
    steps:
    - script: |
        echo "Running tests..."
        # Insert your test commands here

- stage: Build
  displayName: 'Build'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/cicd', 'refs/heads/release'))
  dependsOn: Test
  jobs:
  - job: BuildJob
    displayName: 'Build Project'
    steps:
    - script: |
        echo "Building project..."
        # Insert your build commands here

