trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
  displayName: 'S3 Upload: ecs-bucket-mikhalskyi'
  inputs:
    awsCredentials: 'aws-oidc2'
    regionName: 'us-east-1'
    bucketName: 'ecs-bucket-mikhalskyi'

- task: AWSCLI@1
  inputs:
    awsServiceConnection: 'aws-oidc2'
    awsCommand: 's3 ls'
    regionName: 'us-east-1'
